### ISSUE TITLE
No console.log ?

### ISSUE THREAD

**Issue by Farrand** [CyberCRI/RedWire#525]
![screen](https://cloud.githubusercontent.com/assets/5127325/9495428/c9a677d4-4c0b-11e5-8ac5-94a0dc175a2f.png)

**Comment by drpepper** [comment]
In a transformer or processor, you can use functions like log.warn(). Check
out
https://github.com/CyberCRI/RedWire/wiki/Standard-Toolbox-Reference#logging-functions

2015-08-26 16:02 GMT+02:00 Farrand <notifications@github.com>:
